[2023-07-24 11:25:47,122] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.detect_file manual__2023-07-24T11:25:35.398605+00:00 [queued]>
[2023-07-24 11:25:47,484] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_dag.detect_file manual__2023-07-24T11:25:35.398605+00:00 [queued]>
[2023-07-24 11:25:47,485] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 11:25:47,497] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 11:25:47,507] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 11:25:47,949] {taskinstance.py:1377} INFO - Executing <Task(PythonSensor): detect_file> on 2023-07-24 11:25:35.398605+00:00
[2023-07-24 11:25:48,178] {standard_task_runner.py:52} INFO - Started process 3434 to run task
[2023-07-24 11:25:48,424] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'detect_file', 'manual__2023-07-24T11:25:35.398605+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp9vb4gz7n', '--error-file', '/tmp/tmp5wijrv4f']
[2023-07-24 11:25:48,473] {standard_task_runner.py:80} INFO - Job 39: Subtask detect_file
[2023-07-24 11:25:50,079] {task_command.py:370} INFO - Running <TaskInstance: etl_dag.detect_file manual__2023-07-24T11:25:35.398605+00:00 [running]> on host c03236539c84
[2023-07-24 11:25:52,955] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=detect_file
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T11:25:35.398605+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-24T11:25:35.398605+00:00
[2023-07-24 11:25:52,984] {python.py:66} INFO - Poking callable: <function _detect_file at 0x7f539ef36560>
[2023-07-24 11:25:53,293] {base.py:301} INFO - Success criteria met. Exiting.
[2023-07-24 11:25:53,708] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=detect_file, execution_date=20230724T112535, start_date=20230724T112547, end_date=20230724T112553
[2023-07-24 11:25:54,020] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-24 11:25:54,103] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3434. PIDs of all processes in the group: [3434]
[2023-07-24 11:25:54,116] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3434
[2023-07-24 11:25:54,194] {process_utils.py:75} INFO - Process psutil.Process(pid=3434, status='terminated', exitcode=0, started='11:25:47') (3434) terminated with exit code 0
